#!/bin/sh
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/sbin/scripts

UTC=yes
. /usr/etc/IMP

mount -n -t proc proc /proc
mount -n -t ramfs ramfs /tmp
#added by xichen for mount devpts, ssh use it
mkdir /dev/pts
mount -n -t devpts devpts /dev/pts


# build var directories 
/bin/mkdir -m 0777 /tmp/var
/bin/mkdir -m 0777 /tmp/etc
/bin/mkdir -m 0777 /var/lock
/bin/mkdir -m 0777 /var/log
/bin/mkdir -m 0777 /var/run
/bin/mkdir -m 0777 /var/tmp
/bin/mkdir -m 0777 /tmp/vfs_root
cp -a /usr/etc/* /etc

insmod /lib/linux-kernel-bde.ko
insmod /lib/linux-bcm-core.ko
insmod /lib/linux-bcm-net.ko
insmod /lib/linux-uk-proxy.ko

# Create Broadcom specific devices
mknod /dev/linux-bcm-core c 126 0
mknod /dev/linux-bcm-net c 123 0
mknod /dev/linux-kernel-bde c 127 0
mknod /dev/linux-uk-proxy c 125 0

mknod /dev/poei2c c 154 0

/usr/sbin/systime_from_rtc

# start ethnet
ifconfig $IMP up
route add 255.255.255.255 $IMP

ifconfig eth0 hw ether `/usr/sbin/flash_mac -o`
#ifconfig eth0 192.168.1.156 
ifconfig eth0 up

ifconfig lo 127.0.0.1
route add -net 127.0.0.0 netmask 255.255.0.0 lo > /dev/null 2>&1

#for ntp server
echo -n > /tmp/ntp_start
#start services
/sbin/klogd &
/usr/sbin/cfgmgr 
/usr/sbin/cmd_agent_ap 

/usr/sbin/rc start
#echo "i" > /proc/gpio

/usr/sbin/push_button &
/usr/sbin/rate &

/usr/sbin/aaa &
/usr/sbin/stacking & 

/usr/sbin/mem_monitor &
/usr/sbin/utelnetd &
/usr/sbin/json-server brd &
#/usr/sbin/vlinkscan &
#/usr/sbin/rc printk start
/usr/etc/poe_monitor &
echo 1 > /proc/sys/net/ipv4/ip_forward
echo 1 > /proc/sys/net/ipv6/conf/all/forwarding
/usr/sbin/console
